"""Add role

Revision ID: 354448fa6d36
Revises: 301778ed25f3
Create Date: 2022-02-08 21:37:55.660559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354448fa6d36'
down_revision = '301778ed25f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('role', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'role')
    # ### end Alembic commands ###
